const upgrades = [
    {
        name: "Haven't Smoked Foool",
        cost: { copium: 5, delusion: 0, yarmulkes: 0, trollPoints: 0, hopium: 0 },
        earnings: { copiumPerSecond: 1.5, delusionPerSecond: 0, yarmulkesPerSecond: 0, trollPointsPerSecond: 1, hopiumPerSecond: 0 },
        img: "imgs/ez_blunt.jpg",
    },
    {
        name: "She Old",
        cost: { copium: 0, delusion: 5, yarmulkes: 10, trollPoints: 10, hopium: 0 },
        earnings: { copiumPerSecond: 1, delusionPerSecond: 0, yarmulkesPerSecond: 0, trollPointsPerSecond: 2, hopiumPerSecond: 0 },
        img: "imgs/leo.jpg",
    },
    {
        name: "It's group time!",
        cost: { copium: 10, delusion: 10, yarmulkes: 10, trollPoints: 10, hopium: 0 },
        earnings: { copiumPerSecond: 2, delusionPerSecond: 2, yarmulkesPerSecond: 2, trollPointsPerSecond: 1, hopiumPerSecond: 0 },
        img: "imgs/joker.jpg",
    },
    {
        name: "Standard Dropout",
        cost: { copium: 0, delusion: 30, yarmulkes: 30, trollPoints: 0, hopium: 0 },
        earnings: { copiumPerSecond: 1, delusionPerSecond: 1, yarmulkesPerSecond: 1, trollPointsPerSecond: -2, hopiumPerSecond: 0 },
        img: "imgs/standard_dropout.jpg",
    },
    {
        name: "Is he alive?",
        cost: { copium: 10, delusion: 0, yarmulkes: 50, trollPoints: 35, hopium: 0 },
        earnings: { copiumPerSecond: 1, delusionPerSecond: 0, yarmulkesPerSecond: 7, trollPointsPerSecond: 1, hopiumPerSecond: 0 },
        img: "imgs/is_he_alive.jpg",
    },
    {
        name: "Never Admit Mistakes",
        cost: { copium: 100, delusion: 100, yarmulkes: 0, trollPoints: 0, hopium: 0 },
        earnings: { copiumPerSecond: 2, delusionPerSecond: 4, yarmulkesPerSecond: 0, trollPointsPerSecond: 2.5, hopiumPerSecond: 0 },
        img: "imgs/marv.jpg",
    },
    {
        name: "Party Animals",
        cost: { copium: 50, delusion: 100, yarmulkes: 50, trollPoints: 0, hopium: 0 },
        earnings: { copiumPerSecond: 2, delusionPerSecond: 3, yarmulkesPerSecond: 0, trollPointsPerSecond: 0, hopiumPerSecond: 0 },
        img: "imgs/party_animals.jpg",
    },
    {
        name: "Music",
        cost: { copium: 100, delusion: 25, yarmulkes: 150, trollPoints: 25, hopium: 0 },
        earnings: { copiumPerSecond: 9, delusionPerSecond: -1, yarmulkesPerSecond: 0, trollPointsPerSecond: 0, hopiumPerSecond: 0 },
        img: "imgs/linkin_park.jpg",
    },
    {
        name: "Kamala 2024",
        cost: { copium: 0, delusion: 400, yarmulkes: 0, trollPoints: 0, hopium: 0 },
        earnings: { copiumPerSecond: 4.2, delusionPerSecond: 0, yarmulkesPerSecond: 6.9, trollPointsPerSecond: 0, hopiumPerSecond: 0 },
        img: "imgs/kamala.jpg",
    },
    {
        name: "Yom Kippur",
        cost: { copium: 0, delusion: 0, yarmulkes: 999, trollPoints: 0, hopium: 0 },
        earnings: { copiumPerSecond: 0, delusionPerSecond: 0, yarmulkesPerSecond: 27, trollPointsPerSecond: 0, hopiumPerSecond: 0 },
        img: "imgs/yom_kippur.jpg",
    },
    {
        name: "Email Safety First",
        cost: { copium: 1000, delusion: 0, yarmulkes: 0, trollPoints: 150, hopium: 0 },
        earnings: { copiumPerSecond: 0, delusionPerSecond: 9, yarmulkesPerSecond: -1, trollPointsPerSecond: 0, hopiumPerSecond: 0 },
        img: "imgs/proton.jpg",
    },
    {
        name: "Joker's Rage Level",
        cost: { copium: 500, delusion: 0, yarmulkes: 250, trollPoints: 500, hopium: 0 },
        earnings: { copiumPerSecond: 2, delusionPerSecond: -25, yarmulkesPerSecond: 10, trollPointsPerSecond: 28, hopiumPerSecond: 0 },
        img: "imgs/over_9000.jpg",
    },
    {
        name: "Wife's AirBnb Business",
        cost: { copium: 200, delusion: 400, yarmulkes: 1000, trollPoints: 0, hopium: 0 },
        earnings: { copiumPerSecond: 5, delusionPerSecond: 8, yarmulkesPerSecond: -5, trollPointsPerSecond: 24, hopiumPerSecond: 0 },
        img: "imgs/airbnb.jpg",
    },
    {
        name: "Hard Work Don't Mean Success",
        cost: { copium: 2000, delusion: 0, yarmulkes: 1400, trollPoints: 0, hopium: 0 },
        earnings: { copiumPerSecond: 10, delusionPerSecond: -5, yarmulkesPerSecond: 1, trollPointsPerSecond: 0, hopiumPerSecond: 0 },
        img: "imgs/hard_to_swallow.jpg",
    },
    {
        name: "Captain Degen",
        cost: { copium: 1000, delusion: 1000, yarmulkes: 1000, trollPoints: 1000, hopium: 0 },
        earnings: { copiumPerSecond: 10, delusionPerSecond: 10, yarmulkesPerSecond: 10, trollPointsPerSecond: 10, hopiumPerSecond: 0 },
        img: "imgs/captain_degen.jpg",
        message: "Degenerates, assemble!!!",
    },
    {
        name: "Swing and a Miss",
        cost: { copium: 2400, delusion: 1600, yarmulkes: 0, trollPoints: 0, hopium: 0 },
        earnings: { copiumPerSecond: 24, delusionPerSecond: 16, yarmulkesPerSecond: 0, trollPointsPerSecond: 3, hopiumPerSecond: 0 },
        img: "imgs/swing_and_a_miss.jpg",
    },
    {
        name: "The Savior",
        cost: { copium: 0, delusion: 0, yarmulkes: 2500, trollPoints: 2500, hopium: 0 },
        earnings: { copiumPerSecond: 10, delusionPerSecond: 10, yarmulkesPerSecond: -10, trollPointsPerSecond: 3, hopiumPerSecond: 0 },
        img: "imgs/the_savior.jpg",
    },
    {
        name: "He's an Ancient",
        cost: { copium: 2000, delusion: 0, yarmulkes: 1000, trollPoints: 2000, hopium: 0 },
        earnings: { copiumPerSecond: 5, delusionPerSecond: 0, yarmulkesPerSecond: 27, trollPointsPerSecond: 5, hopiumPerSecond: 0 },
        img: "imgs/farming_sim.jpg",
    },
    {
        name: "Unhackable",
        cost: { copium: 5000, delusion: 2000, yarmulkes: 1500, trollPoints: 0, hopium: 0 },
        earnings: { copiumPerSecond: 45, delusionPerSecond: 30, yarmulkesPerSecond: -3, trollPointsPerSecond: -3, hopiumPerSecond: 0 },
        img: "imgs/unhackable.jpg",
    },
    {
        name: "The Perfect Girl",
        cost: { copium: 3000, delusion: 3000, yarmulkes: 3000, trollPoints: 0, hopium: 0 },
        earnings: { copiumPerSecond: 0, delusionPerSecond: 30, yarmulkesPerSecond: -5, trollPointsPerSecond: 0, hopiumPerSecond: 0 },
        img: "imgs/the_perfect_girl.jpg",
    },
    {
        name: "Kai's wet dream",
        cost: { copium: 5000, delusion: 0, yarmulkes: 4000, trollPoints: 500, hopium: 0 },
        earnings: { copiumPerSecond: 25, delusionPerSecond: 1, yarmulkesPerSecond: 0, trollPointsPerSecond: 1, hopiumPerSecond: 0 },
        img: "imgs/kais_wet_dream.jpg",
    },
    {
        name: "Deal with the devil",
        cost: { copium: 0, delusion: 0, yarmulkes: 10000, trollPoints: 0, hopium: 0 },
        earnings: { copiumPerSecond: -1, delusionPerSecond: 2, yarmulkesPerSecond: 2, trollPointsPerSecond: 1, hopiumPerSecond: 0 },
        img: "imgs/warren_buffet.jpg",
    },
    {
        name: "Face of Defeat",
        cost: { copium: 10000, delusion: 0, yarmulkes: 666, trollPoints: 100, hopium: 0 },
        earnings: { copiumPerSecond: 100, delusionPerSecond: 2, yarmulkesPerSecond: 0, trollPointsPerSecond: -2, hopiumPerSecond: 0 },
        img: "imgs/face_of_defeat.jpg",
    },
    {
        name: "King of Delusion",
        cost: { copium: 0, delusion: 10000, yarmulkes: 2000, trollPoints: 0, hopium: 0 },
        earnings: { copiumPerSecond: 5, delusionPerSecond: 99, yarmulkesPerSecond: 5, trollPointsPerSecond: 0, hopiumPerSecond: 0 },
        img: "imgs/king_of_delusion.jpeg",
    },
    {
        name: "Suss",
        cost: { copium: 12000, delusion: 0, yarmulkes: 0, trollPoints: 0, hopium: 0 },
        earnings: { copiumPerSecond: 25, delusionPerSecond: 0, yarmulkesPerSecond: 0, trollPointsPerSecond: 50, hopiumPerSecond: 0 },
        img: "imgs/morty.PNG",
    },
    {
        name: "Luigi's Idol",
        cost: { copium: 1234, delusion: 0, yarmulkes: 7777, trollPoints: 7777, hopium: 0 },
        earnings: { copiumPerSecond: 12, delusionPerSecond: 0, yarmulkesPerSecond: 40, trollPointsPerSecond: 50, hopiumPerSecond: 0 },
        img: "imgs/luigis_idol.png",
    },
    {
        name: "I don't get this game",
        cost: { copium: 5000, delusion: 5000, yarmulkes: 5000, trollPoints: 5000, hopium: 0 },
        earnings: { copiumPerSecond: -10, delusionPerSecond: 40, yarmulkesPerSecond: 20, trollPointsPerSecond: 30, hopiumPerSecond: 0 },
        img: "imgs/standard.jpg",
    },
    {
        name: "Cookie Clicker",
        cost: { copium: 30000, delusion: 10000, yarmulkes: 20000, trollPoints: 10000, hopium: 0 },
        earnings: { copiumPerSecond: 1, delusionPerSecond: 1, yarmulkesPerSecond: 1, trollPointsPerSecond: 1, hopiumPerSecond: 0 },
        img: "imgs/cookie_clicker.jpg",
    },
    {
        name: "Sex Change",
        cost: { copium: 50000, delusion: 50000, yarmulkes: 0, trollPoints: 0, hopium: 0 },
        earnings: { copiumPerSecond: 250, delusionPerSecond: 250, yarmulkesPerSecond: -10, trollPointsPerSecond: -20, hopiumPerSecond: 0 },
        img: "imgs/sex_change.jpg",
        message: "You feel like you've gotten permanently weaker... (if you had to estimate, you'd say about 3% weaker)",
        miniPrestigeMultiplier: 0.97
    },
    {
        name: "Ultimate Solution",
        cost: { copium: 0, delusion: 25000, yarmulkes: 0, trollPoints: 80000, hopium: 0 },
        earnings: { copiumPerSecond: 92, delusionPerSecond: 97, yarmulkesPerSecond: 0, trollPointsPerSecond: 0, hopiumPerSecond: 0 },
        img: "imgs/use_useless.jpg",
    },
    {
        name: "Fully Autonomous Cars",
        cost: { copium: 80000, delusion: 80000, yarmulkes: 10000, trollPoints: 25000, hopium: 0 },
        earnings: { copiumPerSecond: 75, delusionPerSecond: 20, yarmulkesPerSecond: 10, trollPointsPerSecond: 10, hopiumPerSecond: 0 },
        img: "imgs/elon_tesla.jpg",
    },
    {
        name: "Job Application",
        cost: { copium: 3000, delusion: 55000, yarmulkes: 0, trollPoints: 69000, hopium: 0 },
        earnings: { copiumPerSecond: 300, delusionPerSecond: 0, yarmulkesPerSecond: 0, trollPointsPerSecond: 0, hopiumPerSecond: 0 },
        img: "imgs/job_application.jpg",
    },
    {
        name: "Spit on that thang",
        cost: { copium: 100000, delusion: 0, yarmulkes: 25000, trollPoints: 50000, hopium: 0 },
        earnings: { copiumPerSecond: 80, delusionPerSecond: 0, yarmulkesPerSecond: 25, trollPointsPerSecond: 35, hopiumPerSecond: 0 },
        img: "imgs/hawk_tuah.jpg",
    },
    {
        name: "I'm gonna come",
        cost: { copium: 75000, delusion: 75000, yarmulkes: 0, trollPoints: 50000, hopium: 0 },
        earnings: { copiumPerSecond: -100, delusionPerSecond: 0, yarmulkesPerSecond: -225, trollPointsPerSecond: 500, hopiumPerSecond: 0 },
        img: "imgs/do_not_come.jpg",
    },
    {
        name: "BrOadEn IN God",
        cost: { copium: 150000, delusion: 20000, yarmulkes: 20000, trollPoints: 40000, hopium: 0 },
        earnings: { copiumPerSecond: 500, delusionPerSecond: 500, yarmulkesPerSecond: -10, trollPointsPerSecond: 250, hopiumPerSecond: 0 },
        img: "imgs/boeing.jpg",
    },
    {
        name: "Do not come!",
        cost: { copium: 300000, delusion: 0, yarmulkes: 0, trollPoints: 0, hopium: 0 },
        earnings: { copiumPerSecond: 0, delusionPerSecond: 100, yarmulkesPerSecond: 300, trollPointsPerSecond: 100, hopiumPerSecond: 0 },
        img: "imgs/im_gonna_come.jpg",
    },
    {
        name: "Transcendence",
        cost: { copium: 99999, delusion: 99999, yarmulkes: 99999, trollPoints: 99999, hopium: 0 },
        earnings: { copiumPerSecond: 500, delusionPerSecond: 500, yarmulkesPerSecond: 500, trollPointsPerSecond: 500, hopiumPerSecond: 0 },
        img: "imgs/transcendence.jpg",
        message: "You feel permanently stronger! SPOILER ALERT: in future versions this will lead to another ascendency path.",
        miniPrestigeMultiplier: 1.03
    },
    {
        name: "420",
        cost: { copium: 420000, delusion: 420000, yarmulkes: 420000, trollPoints: 420000, hopium: 0 },
        earnings: { copiumPerSecond: 420, delusionPerSecond: 420, yarmulkesPerSecond: 420, trollPointsPerSecond: 420, hopiumPerSecond: 0 },
        img: "imgs/blaze_it.jpg",
    },
    {
        name: "Pudge",
        cost: { copium: 1000000, delusion: 0, yarmulkes: 0, trollPoints: 1000000, hopium: 0 },
        earnings: { copiumPerSecond: 60, delusionPerSecond: 0, yarmulkesPerSecond: 400, trollPointsPerSecond: 100, hopiumPerSecond: 0 },
        img: "imgs/pudge.jpg",
    },
    {
        name: "WE MADE IT!",
        cost: { copium: 1000000, delusion: 1000000, yarmulkes: 1000000, trollPoints: 1000000, hopium: 0 },
        earnings: { copiumPerSecond: 99, delusionPerSecond: 5, yarmulkesPerSecond: 5, trollPointsPerSecond: 99, hopiumPerSecond: 0 },
        img: "imgs/titanic.jpg",
    },
    {
        name: "Rewriting History",
        cost: { copium: 5000000, delusion: 0, yarmulkes: 0, trollPoints: 0, hopium: 0 },
        earnings: { copiumPerSecond: 25, delusionPerSecond: 0, yarmulkesPerSecond: 1200, trollPointsPerSecond: 0, hopiumPerSecond: 0 },
        img: "imgs/rewriting_history.jpg",
    },
    {
        name: "Hunt for Osama",
        cost: { copium: 5000000, delusion: 1000000, yarmulkes: 5000000, trollPoints: 5000000, hopium: 0 },
        earnings: { copiumPerSecond: 5000, delusionPerSecond: 5000, yarmulkesPerSecond: 5000, trollPointsPerSecond: 5000, hopiumPerSecond: 0 },
        img: "imgs/osama.jpg",
        message: "As you finally corner Osama in a remote mountain hideout, you prepare for a decisive confrontation. However, instead of fighting back, Osama drops his weapon and raises a white flag. With sincerity in his eyes, he says, \"I'm a changed man. All I want now is World Peace.\"\n\nCaught off guard, you sense the truth in his words, feeling the weight of his genuine remorse. With a heavy heart, you choose to spare him, setting the stage for an unexpected alliance that could reshape the future. This pivotal moment challenges your perception of justice and redemption.",
    },
    {
        name: "Hunt for Hussein",
        cost: { copium: 10000000, delusion: 10000000, yarmulkes: 10000000, trollPoints: 10000000, hopium: 0 },
        earnings: { copiumPerSecond: 100000, delusionPerSecond: 0, yarmulkesPerSecond: 0, trollPointsPerSecond: 10000, hopiumPerSecond: -0.01 },
        img: "imgs/obama.jpg",
        message: "Desperate to eliminate the ruthless terrorist Saddam Hussein, you hire a team of elite hitmen. The mission seems straightforward until a devastating mistake changes everything.\nThe hitmen, due to a grave error, confuse their target with Barrack Hussein Obama, a prominent humanitarian and beacon of hope in the war-torn region. When the news breaks that Obama has been assassinated, the world plunges into despair. The humanitarian's death leaves a void, extinguishing the hope he brought to countless lives.\nAs you watch the consequences of this tragic error unfold, you grapple with guilt and the profound realization that sometimes, the lines between good and evil blur. The game takes you on a journey of redemption as you strive to undo the damage and restore hope to a world teetering on the brink of darkness.",
    },
];