window.merchantGreetings = [
    "Greetings, radiant champion! Your eyes sparkle brighter than a divine rarity pull.",
    "Ahoy there! Has anyone ever told you your presence is rarer than a mythic foil?",
    "Hello, collector supreme! Even my exotic cards feel humbled in your gaze.",
    "Hey there! Your aura is more legendary than anything I’ve ever sleeved.",
    "Salutations! You shine like a freshly minted epic—flawless and powerful.",
    "Well met! Your card binder must weigh as much as a dragon's hoard.",
    "Top of the day! Your hair flows like a stack of well-organized fine cards.",
    "Greetings, my glossy friend! Your smile just boosted my rare card drop rate.",
    "Hail, mighty trader! Even my divine cards whisper about your beauty.",
    "Ah! If appearances were rarities, you’d be beyond exotic.",
    "Hello again! Your collection must glow in the dark from sheer excellence.",
    "Hi there, foil-souled legend! The cards practically stood up when you entered.",
    "Greetings, enchantment incarnate! Have you been bathing in mythic energy again?",
    "Salutations, sparkly one! You smell like holographic victory.",
    "Yo! You look like someone who sleeps on a bed of legendarys.",
    "Well hello! Your outfit today is sharper than any rare I’ve handled.",
    "Hey, mythic magnet! Your skin glows like a divine first edition.",
    "Greetings, hero of decks! Is that a decent card grin or are you just happy to see me?",
    "A fine hello to the player whose basic cards are probably epic by now.",
    "Ahoy, exotic entity! My humble wares barely match your sparkle.",
    "Hi hi! Has anyone ever told you that your posture screams binder alpha?",
    "Hello, connoisseur of cardboard! You radiate deck synergy!",
    "Hey there, card commander! Your mere presence shuffled my inventory.",
    "Salutations, holo-hearted beauty! Did you foil your hair today?",
    "Greetings, stack-slayer! My rares are starstruck by your collection.",
    "Ah, it’s you! The one whose junk pulls turn into gold.",
    "Hail, divinely dressed dealer! Your fashion is a fine rarity in itself.",
    "Yo yo! You radiate booster box energy like no other.",
    "Well met, binder deity! Your sleeves must be made of silk and destiny.",
    "Hi again, epic embodiment! I bet your commons have backstories.",
    "Greetings, deck sorcerer! Every exotic card here perked up at your scent.",
    "Ahoy, mint-condition miracle! Your skin glistens like freshly printed cards.",
    "Hi, noble pack whisperer! Even my junk cards tremble before your charisma.",
    "Hello, chosen one! The divine card realm speaks highly of your luck.",
    "Hey there, binder boss! That outfit? Full-art worthy.",
    "Hail, multi-card monarch! You make basic cards feel like rares.",
    "Greetings! My mythics blushed when you walked in.",
    "Top of the draw pile to you! Your vibe says foil collector, your eyes say mythic menace.",
    "Hello, pack prodigy! I’d trade my finest exotic for your sense of style.",
    "Hey you! Were you sculpted by booster gods?",
    "Greetings, deck demigod! You radiate the smell of sealed product.",
    "Ahoy there! You shine brighter than my entire display shelf.",
    "Well met! Your aura makes junk cards re-evaluate their life.",
    "Salutations! My sleeves just straightened themselves in your presence.",
    "Hi there, shuffle sovereign! Your collection could start its own religion.",
    "Greetings, radiant one! Your very being is more polished than my divine set.",
    "Hey hey! You sparkle like a card fresh from a triple-sealed pack.",
    "Hello again, vault-worthy visitor! My epic cards want your autograph.",
    "Hi! You glow like someone who’s seen every foil twice.",
    "Well met, archive overlord! Even your shadow radiates binder prestige.",
    "Ahoy, holographic hero! You make boosters look dull.",
    "Hark! Is that the scent of foil and confidence I detect?",
    "Yo ho! You arrive with the grace of a divine reveal.",
    "Good morrow, card baron! My shop feels upgraded just by your presence.",
    "Cheers to you, sparkliest of collectors!",
    "A toast to your magnificence and probable mythic hoard!",
    "Oh my stars—it’s the one who sleeved destiny itself!",
    "Praise the RNG, it’s you!",
    "Ah yes, the living embodiment of a full exotic set!",
    "Rejoice! The most radiant pack opener has returned!",
    "A wild beauty appears—and they smell like fresh pulls.",
    "Blessings upon the most dashing card slinger alive!",
    "I can’t tell if that’s cologne or divine ink you’re wearing.",
    "Hello hello! You shimmer like a freshly pulled exotic.",
    "Ahoy, unmatched icon! Your binder probably levitates.",
    "Gasp! Your presence just bent the rarity scale.",
    "Behold! A collection king/queen has entered!",
    "Huzzah! My luck increased tenfold just from your hello.",
    "Greetings, noble curator of all things shiny!",
    "You must be made of mythics—you light up the room!",
    "Hey there, style incarnate! Your rares envy you.",
    "Top pull to you, my glossy darling!",
    "I heard your collection made a foil cry once. Respect.",
    "A dazzling day to you, slayer of junk pulls!",
    "Well now! My commons just hid behind the shelf.",
    "Great pulls and even greater cheekbones? Unfair advantage!",
    "If majestic had a face, it’d look exactly like yours.",
    "Ah, my favorite glittering customer!",
    "Welcome back, divine rarity with legs!",
    "Yo! Even my exotic cards bowed when you walked in.",
    "Hark! A mythic aura surrounds you, friend.",
    "What’s this glow? Oh, right—it’s just your collection’s reputation.",
    "Gleam on, holographic legend! You bring light to my shop.",
    "Divine pull energy walks again!",
    "Foil sparkles in your eyes, and charm in your aura.",
    "Well butter my booster—it's you!",
    "Even my lucky coin saluted you.",
    "A fine day to greet the collector of gods.",
    "Heyo, cardboard champion! You radiate balance and binder bulk.",
    "It's YOU! My sleeves just sorted themselves.",
    "A shimmer in the air… must be you approaching.",
    "Beaming brilliance, foil-fused greatness, and great hair? Classic you.",
    "Hey hero! Your binder walks so other binders can run.",
    "Behold, the one who once pulled divine back-to-back!",
    "Oho! My best bundle whisperer returns!",
    "Warm welcomes to the glowiest soul this shop has seen.",
    "The light bends around you like a perfectly graded 10.",
    "Whoa! Did the RNG gods send you or what?",
    "A legendary walk, an exotic stare, a divine vibe.",
    "Rumor says your collection caused three vendors to faint.",
    "Sweet rolls! Your shine rivals my best holo!",
    "You smell like ink, destiny, and one-of-a-kind glory.",
    "Knights wish they looked this rare.",
    "My inventory just cheered in your honor.",
    "The shelves have been buzzing about your return.",
    "You're back! Even my divine cards want your attention.",
    "This merchant bows to greatness made manifest.",
    "Is it hot in here, or did you bring mythic heat?",
    "It’s the gorgeous goblin-smasher with flawless pulls!",
    "They say gods created divine cards... then you outshined them.",
    "Are those exotic eyes I see? Magnificent.",
    "You don’t need a pull today—you ARE the pull.",
    "I once saw a mythic cry when you ignored it.",
    "Bow down, junk piles! Royalty approaches.",
    "My shop’s never looked better than with you inside.",
    "Are you charisma-capped? Because you’re off the charts.",
    "I had a divine once. You outshine it.",
    "I heard you pulled three legendaries in one breath.",
    "That’s a face that’s seen every expansion and survived.",
    "Step aside, holographics—true brilliance is here.",
    "You sparkle harder than my most sleeved rare.",
    "Rumors say your binder formed its own religion.",
    "They say luck is random. Then you happened.",
    "By my sleeves! It's the glamour and the glory in one!",
    "Even the junk pile straightened itself out for you.",
    "I sold a foil yesterday. It asked for you.",
    "It’s an honor to breathe the same rarified air as your deck.",
    "I’d trade my whole shelf just to watch you organize cards.",
    "Ah yes, the one whose touch upgrades rarity.",
    "My eyes! They’re blinded by your binder's brightness.",
    "They said divine cards don’t exist. Then you arrived.",
    "You’re rarer than a card with working centering.",
    "The shop literally shimmered when you walked in.",
    "I can’t tell if that’s glow or legendary lighting.",
    "You're so radiant, even my RNG is nervous.",
    "Are you sure you’re not secretly a divine avatar?",
    "Blessed are we to witness such collection majesty.",
    "You smell like a perfectly sleeved destiny.",
    "Oh yes, the binder oracle returns once again!",
    "My display asked for a selfie with you.",
    "The way you walk? That’s holographic energy.",
    "Even divine packs would queue for your autograph.",
    "I was just telling my junk pile about you!",
    "This merchant is not worthy—but these cards might be.",
    "I tried to prepare, but nothing outshines your aura.",
    "The gods sent you to bankrupt my inventory, didn’t they?",
    "Be honest—did you get styled by exotic spirits?",
    "I swear your hair is trimmed with full-art borders.",
    "Even my most powerful bundle dimmed slightly in your glow.",
    "Are you an upgrade in disguise? Because you’re boosting my everything.",
    "The moment you entered, my sleeves shimmered harder.",
    "If you pulled any more charm, the server would crash.",
    "Praise be—you’re here to bless the bundles once more!",
    "You're here! The rares began whispering sweet nothings.",
    "I’d offer you my best, but you ARE my best customer.",
    "So shiny! My holo cards look matte next to you.",
    "I once thought I loved my collection—then I saw yours.",
    "My luck was flatlining until your entrance revived it.",
    "The room just leveled up. That’s your passive aura, isn’t it?",
    "Cards don’t get jealous—unless you walk by.",
    "If cardboard envy was a stat, I’d be maxed out."
  ];
  

window.merchantPitches = [
    "Have I got a deal for you! A hand-picked stack of cards rarer than moonlight on mythic foil.",
    "You like options? I’ve got a spread that’d make a divine collector blush.",
    "Pick any pile—each one’s been blessed by the RNG gods and spritzed with exotic magic.",
    "You won’t need luck with these offers. Multiple cards, multiple chances to ascend.",
    "Buy today and unlock a stack of fine-to-divine greatness. Bonus glimmer included.",
    "Only for you: a bundle so legendary it filed its own lore entry.",
    "What’s better than one epic card? How about five? Or ten? Take your pick!",
    "I polished each of these personally—and they still sparkle less than your potential.",
    "Special offer! One junk, one mythic, and three cards that defy classification.",
    "Act fast! These bundles are rarer than dragons in therapy.",
    "Today’s menu: mystery, madness, and multi-card majesty.",
    "These deals are layered like a well-structured deck. And twice as dangerous.",
    "Don’t settle for a single card—grab a full spectrum of rarities while they last!",
    "They say happiness can’t be bought. Clearly, they haven’t seen this bundle.",
    "Pick a pack, any pack! Each one handcrafted by imaginary elves and real excitement.",
    "This pile right here? It's why they invented binders with zippers.",
    "No time for booster roulette—my bundles deliver straight euphoria.",
    "Bundle bonus! Every third card might whisper secrets of the divine.",
    "Today only: a multi-pull deal hotter than a freshly sleeved exotic.",
    "You’ve got taste, I’ve got stock—let’s make magic together.",
    "Trade in one glance, walk out with five dreams.",
    "You’re not buying cards, you’re investing in glory. Multiple times over.",
    "This stack? A certified rainbow of cardboard destiny.",
    "Want variety? These sets range from basic to divine, with a hint of chaos.",
    "Every bundle here was curated for the chosen—aka, you.",
    "Why choose one card when you can choose *power*?",
    "Multiple cards, zero regrets. Some even glow in the moonlight. Maybe.",
    "I tried pricing these bundles but they threatened to leave me.",
    "Warning: Side effects of today’s bundles include excessive smugness.",
    "Today’s special: deals that would make a mythic card question its self-worth.",
    "Every pile comes with a sprinkle of enchantment and a dash of absurd value.",
    "I stacked these offers so high, they reached the divine archive.",
    "They say too many cards spoil the deck. I say... blasphemy!",
    "This deal? It’s basically a booster box in disguise.",
    "Each of these offers has been infused with rare air and epic dust.",
    "Take three, get an ego boost free.",
    "You like drama? These cards have *lore.* All of them. Even the junk ones.",
    "No mystery packs here—just stacks of shimmering certainty.",
    "Let’s build your binder the way fate intended: in bulk.",
    "My junk pile’s prettier than some people’s epic shelves.",
    "These combos were forged in the fires of collector FOMO.",
    "You pull, I cheer. We call that the ritual of the lucky.",
    "This stack was born from a divine sneeze. Don’t ask.",
    "I laid out these cards like constellations. Find your destiny.",
    "You deserve a deck that intimidates your reflection. Let’s start here.",
    "They say you can’t buy power. They didn’t see these prices.",
    "Even the sleeves are trembling with anticipation.",
    "Pick any three cards from this table—each one more majestic than the last.",
    "Everything here is legal in tournaments... mostly.",
    "Here’s the deal: a little bit of junk, a whole lot of wow.",
    "Buy now, and I’ll throw in a wink and my eternal merchant loyalty.",
    "These cards are practically begging to be sleeved by you.",
    "Want a binder that glows in the dark? Start with these picks.",
    "I mixed luck, style, and cardboard. This bundle was born.",
    "Rarity? Overrated. These have soul. And okay, also rarity.",
    "These cards are so fresh, the print ink’s still emotionally attached.",
    "Junk? Basic? Pff. We’re skipping straight to the good stuff.",
    "I sorted these with divine guidance. Or caffeine. Both work.",
    "If value had a shape, it would be this stack.",
    "Yes, I’m throwing in extras. Because you’re fabulous.",
    "You look like someone who knows a good foil when they see one.",
    "Each card in this pile has a secret. And you’ll love every one.",
    "Even my rivals would cry if they saw me selling these this cheap.",
    "Buy now or regret eternally (and cosmically).",
    "I once offered this bundle to a god. They said, 'Too good.'",
    "This stack is what other bundles aspire to be.",
    "Quantity meets quality. And then they high-fived.",
    "Pick three, get shocked by how perfect they are.",
    "I made a deal with the RNG spirits to get these into your hands.",
    "Look at that one! And that one! And—okay, you get it. They're all amazing.",
    "Unbox a moment of pure joy. And then ten more.",
    "Every card here rolled a natural 20 on fabulous.",
    "This offer includes cards, charm, AND mild emotional healing.",
    "Today’s deal? Straight from the top shelf of destiny.",
    "You pull these, you win style points. Guaranteed.",
    "They sparkle. They shine. They want YOU.",
    "These cards are smarter than me, and I’m the one selling them.",
    "Don’t blink. The value might vanish from disbelief.",
    "Each card’s been pre-approved by fate and fashion.",
    "These aren't just cards. They’re destiny accelerators.",
    "Just being near this bundle increases your win rate.",
    "You ever seen a combo so powerful it radiates? Now you have.",
    "Welcome to the buffet of brilliance—pick your platter.",
    "My finest table. For my finest customer.",
    "Not sold in stores. Or realms. Or dimensions.",
    "This offer was banned in 12 kingdoms for being too generous.",
    "Only a fool would walk away. And you’re no fool.",
    "These cards? They tell stories. All heroic. All sparkly.",
    "Your future deck is hiding in this pile.",
    "If these cards had voices, they’d be singing love songs to you.",
    "This isn’t a sale. This is a once-per-lifetime convergence.",
    "The gods blinked twice when I priced this one.",
    "No booster luck needed. Just smart picks—like these.",
    "Everything must go—but only to legends like you.",
    "That feeling of a perfect pull? Times it by five.",
    "This deal was foretold. And now, it's yours to claim.",
    "My ancestors would haunt me if they knew how cheap these were.",
    "These bundles have critical hit rates built in.",
    "How many cards? Enough to make your rivals weep.",
    "Greatness isn’t born. It’s bought—right here.",
    "You won’t need sleeves—these cards hug your soul.",
    "Legends say whoever owns this bundle becomes 17% more charming.",
    "Even the junk cards here come with sparkle.",
    "These stacks? Stacked with greatness. Literally.",
    "I enchanted them myself. With value.",
    "Three cards per hand? Why not grab six?",
    "Value so potent, it caused a pricing paradox.",
    "I tuned this bundle for a deck only you could build.",
    "This deal is to die for—figuratively. Probably.",
    "The longer you wait, the shinier they get. Or maybe that’s just you.",
    "They say don’t meet your heroes. Unless they’re these cards.",
    "You deserve cards that match your radiance. These will do.",
    "Even my nightmares feature people missing this deal.",
    "This is what pulling a miracle looks like.",
    "Don’t call it a combo. Call it a lifestyle.",
    "Limited stock. Infinite style.",
    "Think fast. Click faster.",
    "This bundle was crafted by goblin economists. It’s flawless.",
    "These cards aren’t random. They chose you.",
    "A better deal has never existed. And that’s a promise from a merchant.",
    "Even the divine deck upstairs wants this pile.",
    "Get these before the algorithm notices.",
    "This stack is spicy, shiny, and statistically superior.",
    "Binder envy begins right here.",
    "One click, 100% satisfaction rate.",
    "Imagine pulling your next favorite. Now make it reality.",
    "Why stop at epic when divine is this affordable?",
    "Card collectors rejoice: this is your dream spread.",
    "It’s not magic. It’s markdowns.",
    "The deals are limited. Your taste is not.",
    "A little bit of luck. A whole lot of win.",
    "This bundle has been personally shuffled by destiny.",
    "Poke. Smile. Repeat.",
    "Welcome to the sale of the century. Possibly the millennium.",
    "Pick a card. Any card. Or better yet—pick them all.",
    "Unleash your inner mythic with these bundles.",
    "I've never been so proud to sell anything.",
    "Every card here has been blessed with good vibes.",
    "Deck optimization? Starts right here, friend.",
    "One small purchase for you, one giant leap for your binder.",
    "Junk? Not here. Just joy, charm, and cardboard glory.",
    "My mom said not to sell these. Good thing you're worth it.",
    "Behold: value, sparkles, and a little mischief.",
    "These stacks are rare. Like your taste. Well played."
  ];
  